apiVersion: v2
name: traefik
description: Mod chart for traefik with AVP support
type: application
version: 0.1.0

dependencies:
- name: traefik
  version: 36.2.0-rc1
  repository: "https://traefik.github.io/charts"
